<?php

namespace App\Filament\Resources;

use App\Filament\Resources\OrderResource\Pages;
use App\Filament\Resources\OrderResource\RelationManagers;
use App\Models\Order;
use Filament\Forms;
use Filament\Forms\Components\TextInput;
use Filament\Resources\Form;
use Filament\Resources\Resource;
use Filament\Resources\Table;
use Filament\Tables;
use Filament\Tables\Columns\TextColumn;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class OrderResource extends Resource
{
    protected static ?string $model = Order::class;

    protected static ?string $navigationIcon = 'heroicon-o-archive';
    protected static ?string $navigationGroup = 'Order Management';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
//                TextInput::make('user.name')
//                    ->required()->label('Order By'),
                TextInput::make('items_count')
                    ->required(),
                TextInput::make('paid_in')
                    ->required()
                    ->maxLength(255),
                TextInput::make('subtotal_amount')->suffix('Rs'),
                TextInput::make('discount_amount')->suffix('Rs'),
                TextInput::make('tax_amount')->suffix('Rs'),
                TextInput::make('total_amount')
                    ->required()->suffix('Rs'),

            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('user.name')
                ->label('Order By'),
                TextColumn::make('items_count')
                ->label('Items'),
                TextColumn::make('subtotal_amount')
                ->label('Amount'),
                TextColumn::make('discount_amount')
                ->label('Discount'),
                TextColumn::make('tax_amount')
                ->label('Tax'),
                TextColumn::make('total_amount')
                ->label('Total Amount'),
                TextColumn::make('paid_in')->extraAttributes(['class'=>'capitalize']),
                TextColumn::make('created_at')
                    ->dateTime('h:i:s A d-M-Y'),
            ])->defaultSort('created_at','asc')
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
//                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\DeleteBulkAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            RelationManagers\ItemsRelationManager::class,
            //
        ];
    }


    public static function getPages(): array
    {
        return [
            'index' => Pages\ListOrders::route('/'),
            'create' => Pages\CreateOrder::route('/create'),
            'view' => Pages\ViewOrder::route('/{record}'),
            'edit' => Pages\EditOrder::route('/{record}/edit'),
        ];
    }

    public static function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
}
